-------------------------------------------------------------------------
*   PONTIFÍCIA UNIVERSIDADE CATÓLICA DE MINAS GERAIS
*   PROFESSOR: VICTOR SALES SILVA
*   ALUNO: Matheus Lopes Lourenço
*   MATRICULA: 1666264
*   E-MAIL: 1666264@sga.pucminas.br
*   ATIVIDADE: EXEMPLO DE LEITURA DE ARQUIVO EM FORMATO JSON UTILIZANDO PANDAS
-------------------------------------------------------------------------

# IMPORTAÇÃO DAS BIBLIOTECAS

In [1]:
import pandas as pd

# DEFINIÇÃO DAS VARIÁVEIS

In [2]:
arquivo = 'C:\\Users\\negri\\OneDrive\\Documentos\\GitHub\\Hashtag_AnaliseDados\\Python\\Cursos\\PUC Ciência de Dados\\Projetos\\Preparação e Integração de Dados\\02_Aula\\Bases de dados\\DADOS_EXAMES.csv'

# LEITURA DO ARQUIVO CSV USANDO PANDAS

In [3]:
df = pd.read_csv(arquivo, sep=';')

# EXIBINDO UMA AMOSTRA DOS DADOS

In [4]:
df.head(5)

,IdUnidadeAtendimento,Cidade,Estado,Bairro,NumPedidoMedico,IdExame,Exame,SiglaExame,Material,SetorExame,QtdAmostrasColhidas,QtdExames,PrecoExame,DataPrevistaResultado,DataLiberacaoResultado
0,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-6217,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2022-03-29 22:43:00.000,2022-03-25 18:18:00.000
1,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11486,3369,PARASITOLÓGICO,FP,FEZES,COPROLOGIA,1,1,"7,6343",2022-02-22 14:43:00.000,2022-02-22 09:01:43.000
2,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11818,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2022-03-08 14:43:00.000,2022-02-28 05:52:40.000
3,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11937,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2022-01-11 14:43:00.000,2022-01-05 07:20:58.000
4,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-12091,3370,GRAM - BACTERIOSCOPIA,GRAM-U,URINA,MICROBIOLOGIA,1,1,"1,7025",2023-01-05 20:43:00.000,2023-01-05 15:16:01.000

# EXIBINDO OS METADADOS (SCHEMA) DO ARQUIVO

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   IdUnidadeAtendimento    500000 non-null  int64
 1   Cidade                  500000 non-null  object
 2   Estado                  500000 non-null  object
 3   Bairro                  500000 non-null  object
 4   NumPedidoMedico         500000 non-null  object
 5   IdExame                 500000 non-null  int64
 6   Exame                   500000 non-null  object
 7   SiglaExame              500000 non-null  object
 8   Material                500000 non-null  object
 9   SetorExame              500000 non-null  object
 10  QtdAmostrasColhidas     500000 non-null  int64
 11  QtdExames               500000 non-null  int64
 12  PrecoExame              500000 non-null  object
 13  DataPrevistaResultado   500000 non-null  object
 14  DataLiberacaoResultado  500000 non-null  object
dtypes: int64(4), object(11)
memory usage: 57.2+ MB

In [6]:
df.head(10)

,IdUnidadeAtendimento,Cidade,Estado,Bairro,NumPedidoMedico,IdExame,Exame,SiglaExame,Material,SetorExame,QtdAmostrasColhidas,QtdExames,PrecoExame,DataPrevistaResultado,DataLiberacaoResultado
0,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-6217,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2022-03-29 22:43:00.000,2022-03-25 18:18:00.000
1,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11486,3369,PARASITOLÓGICO,FP,FEZES,COPROLOGIA,1,1,"7,6343",2022-02-22 14:43:00.000,2022-02-22 09:01:43.000
2,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11818,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2022-03-08 14:43:00.000,2022-02-28 05:52:40.000
3,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11937,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2022-01-11 14:43:00.000,2022-01-05 07:20:58.000
4,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-12091,3370,GRAM - BACTERIOSCOPIA,GRAM-U,URINA,MICROBIOLOGIA,1,1,"1,7025",2023-01-05 20:43:00.000,2023-01-05 15:16:01.000
5,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-12091,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,"9,1419",2023-01-11 14:43:00.000,2023-01-08 07:15:27.000
6,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14385,3371,ZINCO (SORO),ZN-SO,SANGUE,TOXICOLOGIA,1,1,"8,0752",2022-01-09 14:43:00.000,2022-01-08 02:36:45.000
7,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14488,3372,HEMOGRAMA,HG,SANGUE,LINHA VERMELHA,1,1,"7,6797",2022-02-08 14:43:00.000,2022-02-07 15:39:16.000
8,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14494,3373,TESTE DE SEXAGEM FETAL,TSF,SANGUE,BIOLOGIA MOLECULAR,1,1,"7,9637",2022-03-30 14:43:00.000,2022-03-30 10:14:45.000
9,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14564,3374,MICOBACTÉRIAS - CULTURA,CT-BK,DIVERSOS,MICROBIOLOGIA,1,1,"7,5503",2021-06-28 14:43:00.000,2021-06-15 13:10:34.000

# AJUSTAR O SCHEMA DOS DADOS, SE NECESSÁRIO

In [7]:
df['Cidade'] = df['Cidade'].astype('string')
df['Estado'] = df['Estado'].astype('string')
df['Bairro'] = df['Bairro'].astype('string')
df['NumPedidoMedico'] = df['NumPedidoMedico'].astype('string')
df['Exame'] = df['Exame'].astype('string')
df['SiglaExame'] = df['SiglaExame'].astype('string')
df['Material'] = df['Material'].astype('string')
df['SetorExame'] = df['SetorExame'].astype('string')
df['PrecoExame'] = df['PrecoExame'].str.replace(',','.').astype('double')
df['DataPrevistaResultado'] = df['DataPrevistaResultado'].astype('datetime64[ns]')
df['DataLiberacaoResultado'] = df['DataLiberacaoResultado'].astype('datetime64[ns]')

In [8]:
display(df.head(10))

,IdUnidadeAtendimento,Cidade,Estado,Bairro,NumPedidoMedico,IdExame,Exame,SiglaExame,Material,SetorExame,QtdAmostrasColhidas,QtdExames,PrecoExame,DataPrevistaResultado,DataLiberacaoResultado
0,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-6217,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,9.1419,2022-03-29 22:43:00,2022-03-25 18:18:00
1,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11486,3369,PARASITOLÓGICO,FP,FEZES,COPROLOGIA,1,1,7.6343,2022-02-22 14:43:00,2022-02-22 09:01:43
2,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11818,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,9.1419,2022-03-08 14:43:00,2022-02-28 05:52:40
3,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-11937,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,9.1419,2022-01-11 14:43:00,2022-01-05 07:20:58
4,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-12091,3370,GRAM - BACTERIOSCOPIA,GRAM-U,URINA,MICROBIOLOGIA,1,1,1.7025,2023-01-05 20:43:00,2023-01-05 15:16:01
5,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-12091,3368,URINA - CULTURA,CTU,URINA,MICROBIOLOGIA,1,1,9.1419,2023-01-11 14:43:00,2023-01-08 07:15:27
6,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14385,3371,ZINCO (SORO),ZN-SO,SANGUE,TOXICOLOGIA,1,1,8.0752,2022-01-09 14:43:00,2022-01-08 02:36:45
7,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14488,3372,HEMOGRAMA,HG,SANGUE,LINHA VERMELHA,1,1,7.6797,2022-02-08 14:43:00,2022-02-07 15:39:16
8,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14494,3373,TESTE DE SEXAGEM FETAL,TSF,SANGUE,BIOLOGIA MOLECULAR,1,1,7.9637,2022-03-30 14:43:00,2022-03-30 10:14:45
9,713,BELO HORIZONTE,MG,FUNCIONÁRIOS,PED-14564,3374,MICOBACTÉRIAS - CULTURA,CT-BK,DIVERSOS,MICROBIOLOGIA,1,1,7.5503,2021-06-28 14:43:00,2021-06-15 13:10:34

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   IdUnidadeAtendimento    500000 non-null  int64
 1   Cidade                  500000 non-null  string
 2   Estado                  500000 non-null  string
 3   Bairro                  500000 non-null  string
 4   NumPedidoMedico         500000 non-null  string
 5   IdExame                 500000 non-null  int64
 6   Exame                   500000 non-null  string
 7   SiglaExame              500000 non-null  string
 8   Material                500000 non-null  string
 9   SetorExame              500000 non-null  string
 10  QtdAmostrasColhidas     500000 non-null  int64
 11  QtdExames               500000 non-null  int64
 12  PrecoExame              500000 non-null  float64
 13  DataPrevistaResultado   500000 non-null  datetime64[ns]
 14  DataLiberacaoResultado  500000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(4), string(8)
memory usage: 57.2 MB