# **Parte 1: Índice Dow Jones**

Análise Gráfica Inicial

Carregue a série, faça os ajustes de tipo de dado necessários e plote o gráfico de linha da variável Price.

Responda:

*   Graficamente, a série possui indicativo de estacionariedade?
*   É possível identificar períodos com variações atípicas? Se sim, quais?

## **Análise Inicial**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import kpss

df = pd.read_csv('/content/indice_dowjones.csv', sep=',')
df.head(5)

           Date      Price       Open       High        Low     Vol. Change %
0  Dec 31, 2019  28,538.44  28,414.64  28,547.35  28,376.49  193.34M    0.27%
1  Dec 30, 2019  28,462.14  28,654.76  28,664.69  28,428.98  185.07M   -0.64%
2  Dec 27, 2019  28,645.26  28,675.34  28,701.66  28,608.98  184.93M    0.08%
3  Dec 26, 2019  28,621.39  28,539.46  28,624.10  28,535.15  155.97M    0.37%
4  Dec 24, 2019  28,515.45  28,572.57  28,576.80  28,503.21   95.29M   -0.13%

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])
df.set_index("Date", inplace=True)
df.sort_index(inplace=True)
df.head(5)

               Price      Open      High       Low Vol. Change %
Date
2009-01-05  8,952.89  9,027.13  9,093.47  8,841.70    -   -0.91%
2009-01-06  9,015.10  8,954.57  9,175.19  8,868.07    -    0.69%
2009-01-07  8,769.70  8,996.94  8,996.94  8,690.45    -   -2.72%
2009-01-08  8,742.46  8,769.94  8,807.14  8,593.52    -   -0.31%
2009-01-09  8,599.18  8,738.80  8,800.45  8,541.75    -   -1.64%

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2766 entries, 2009-01-05 to 2019-12-31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Price     2766 non-null   object
 1   Open      2766 non-null   object
 2   High      2766 non-null   object
 3   Low       2766 non-null   object
 4   Vol.      2766 non-null   object
 5   Change %  2766 non-null   object
dtypes: object(6)
memory usage: 151.3+ KB

In [ ]:
num_ajustado = df['Price'].str.replace(',', '').astype(float)
df['Price'] = num_ajustado
df.head(5)

              Price      Open      High       Low Vol. Change %
Date
2009-01-05  8952.89  9,027.13  9,093.47  8,841.70    -   -0.91%
2009-01-06  9015.10  8,954.57  9,175.19  8,868.07    -    0.69%
2009-01-07  8769.70  8,996.94  8,996.94  8,690.45    -   -2.72%
2009-01-08  8742.46  8,769.94  8,807.14  8,593.52    -   -0.31%
2009-01-09  8599.18  8,738.80  8,800.45  8,541.75    -   -1.64%

In [ ]:
num_ajustado = df['Open'].str.replace(',', '').astype(float)
df['Open'] = num_ajustado
df.head(5)

              Price     Open      High       Low Vol. Change %
Date
2009-01-05  8952.89  9027.13  9,093.47  8,841.70    -   -0.91%
2009-01-06  9015.10  8954.57  9,175.19  8,868.07    -    0.69%
2009-01-07  8769.70  8996.94  8,996.94  8,690.45    -   -2.72%
2009-01-08  8742.46  8769.94  8,807.14  8,593.52    -   -0.31%
2009-01-09  8599.18  8738.80  8,800.45  8,541.75    -   -1.64%

In [ ]:
num_ajustado = df['High'].str.replace(',', '').astype(float)
df['High'] = num_ajustado
df.head(5)

              Price     Open     High       Low Vol. Change %
Date
2009-01-05  8952.89  9027.13  9093.47  8,841.70    -   -0.91%
2009-01-06  9015.10  8954.57  9175.19  8,868.07    -    0.69%
2009-01-07  8769.70  8996.94  8996.94  8,690.45    -   -2.72%
2009-01-08  8742.46  8769.94  8807.14  8,593.52    -   -0.31%
2009-01-09  8599.18  8738.80  8800.45  8,541.75    -   -1.64%

In [ ]:
num_ajustado = df['Low'].str.replace(',', '').astype(float)
df['Low'] = num_ajustado
df.head()

              Price     Open     High      Low Vol. Change %
Date
2009-01-05  8952.89  9027.13  9093.47  8841.70    -   -0.91%
2009-01-06  9015.10  8954.57  9175.19  8868.07    -    0.69%
2009-01-07  8769.70  8996.94  8996.94  8690.45    -   -2.72%
2009-01-08  8742.46  8769.94  8807.14  8593.52    -   -0.31%
2009-01-09  8599.18  8738.80  8800.45  8541.75    -   -1.64%

In [ ]:
ajuste = df['Vol.'].str.replace('-', '0').str.replace('M', '', regex=False).astype(float)
df['Vol.'] = ajuste
df.head()

              Price     Open     High      Low  Vol. Change %
Date
2009-01-05  8952.89  9027.13  9093.47  8841.70   0.0   -0.91%
2009-01-06  9015.10  8954.57  9175.19  8868.07   0.0    0.69%
2009-01-07  8769.70  8996.94  8996.94  8690.45   0.0   -2.72%
2009-01-08  8742.46  8769.94  8807.14  8593.52   0.0   -0.31%
2009-01-09  8599.18  8738.80  8800.45  8541.75   0.0   -1.64%

In [ ]:
ajuste = df['Change %'].str.replace('%', '0').astype(float)
df['Change %'] = ajuste
df.head()

              Price     Open     High      Low  Vol.  Change %
Date
2009-01-05  8952.89  9027.13  9093.47  8841.70   0.0     -0.91
2009-01-06  9015.10  8954.57  9175.19  8868.07   0.0      0.69
2009-01-07  8769.70  8996.94  8996.94  8690.45   0.0     -2.72
2009-01-08  8742.46  8769.94  8807.14  8593.52   0.0     -0.31
2009-01-09  8599.18  8738.80  8800.45  8541.75   0.0     -1.64

In [ ]:
# Gráfico de Correlação das Variáveis
plt.figure(figsize=(12, 6))
#sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm', fmt='.2f', center=0)
sns.heatmap(df.corr(),annot=True, cmap='coolwarm', fmt='.2f', center=0)
plt.show()

### **Validações de Variações e Estacionariedade**

In [ ]:
plt.figure(figsize=(20, 6))
plt.plot(df['Price'], color='green')
plt.title('Preço do Índice Dow Jones', fontweight='bold', fontsize='15')
plt.xlabel('Data', fontsize=9, fontweight='bold')
plt.xticks(rotation=45, fontsize=7)
plt.ylabel('Preço', fontsize=9, fontweight='bold')
plt.show()

### **Resultados Íniciais**

Para que uma **série temporal seja considerada estacionária**, espera-se que suas **principais características estatísticas**, como a **média e a variância**, permaneçam **aproximadamente constantes ao longo do tempo**. **A partir da análise gráfica inicial**, observa-se que os **valores da série apresentam uma tendência de crescimento e variações ao longo do período analisado**. Dessa forma, há **indícios de que a série não apresenta estacionariedade**. **Entretanto, essa conclusão visual deverá ser validada posteriormente por meio de testes estatísticos**, como o ADF e o KPSS, que permitirão confirmar matematicamente se a série é ou não estacionária.

Em relação a quedas bruscas nos resultados, é observado o seguinte:
* 2009: forte queda e recuperação, correspondente ao período da crise financeira de 2008.
* 2011: período de queda e maior volatilidade.
* 2015–2016: novas quedas expressivas, principalmente próximas de 2015 e início de 2016.
* 2018: aumento da volatilidade, com uma queda bastante acentuada no final do ano.
* 2019: também aparecem oscilações e uma queda significativa antes da recuperação e dos novos máximos.

## **Testes Estatísticos de Estacionariedade**

Execute as funções dos **testes ADF (Augmented Dickey-Fuller) e KPSS (Kwiatkowski-Phillips-Schmidt-Shin)** para a série de preços.

Responda e interprete:

*   Qual a conclusão do Teste ADF ?
*   Qual a conclusão do Teste KPSS ?


# **Autocorrelação (ACF) e Autocorrelação Parcial (PACF)**

*   Gere os gráficos de ACF e PACF para a série do Dow Jones e descreva o comportamento observado.


# **Transformação e Diferenciação**

* Caso a série não seja estacionária, aplique a primeira diferença
* Aplique novamente o Teste ADF sobre a série diferenciada.
* Gere os gráficos de ACF e PACF para série diferenciada.


**Responda: A série tornou-se estacionária após a diferenciação?**

### **Normalização dos Dados**

In [ ]:
import scipy.stats as stats
import matplotlib.pyplot as plt

stats.probplot(df["Price"].dropna(), dist="norm", plot=plt)

plt.title("QQ Plot - Preço do Dow Jones")
plt.show()

In [ ]:
from scipy.stats import shapiro

resultado = shapiro(df["Price"].dropna())

print("Estatística:", resultado.statistic)
print("P-valor:", resultado.pvalue)

if resultado.pvalue < 0.05:
    print("Os dados NÃO apresentam distribuição normal.")
else:
    print("Os dados apresentam distribuição normal.")

In [ ]:
df["Retorno"] = df["Price"].pct_change()
df["Retorno"].dropna().head()

In [ ]:
stats.probplot(df["Retorno"].dropna(), dist="norm", plot=plt)

plt.title("QQ Plot - Retorno do Dow Jones")
plt.show()

In [ ]:
from scipy.stats import shapiro

resultado = shapiro(df["Retorno"].dropna())

print("Estatística:", resultado.statistic)
print("P-valor:", resultado.pvalue)

if resultado.pvalue < 0.05:
    print("Os dados NÃO apresentam distribuição normal.")
else:
    print("Os dados apresentam distribuição normal.")

### **Ajuste na Normalização**

In [ ]:
from sklearn.preprocessing import StandardScaler

serie = df["Price"].dropna()
scaler = StandardScaler()
df["Price_Normalizado"] = scaler.fit_transform(
    df[["Price"]]
)

print("Média:", df["Price_Normalizado"].mean())
print("Desvio padrão:", df["Price_Normalizado"].std())

In [ ]:
stats.probplot(
    df["Price_Normalizado"].dropna(),
    dist="norm",
    plot=plt
)

plt.title("QQ Plot - Price Normalizado")
plt.show()

In [ ]:
sns.distplot(df["Price_Normalizado"].dropna())
plt.show()

In [ ]:
sns.histplot(df["Price"].dropna(), kde=True)
plt.show()

### **Testes Estatísticos**

In [ ]:
# Teste de ADF
from statsmodels.tsa.stattools import adfuller

resultado_adf = adfuller(df["Price_Normalizado"].dropna())

print("Teste ADF")
print("Estatística:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

if resultado_adf[1] < 0.05:
    print("Resultado: A série é ESTACIONÁRIA.")
else:
    print("Resultado: A série NÃO é ESTACIONÁRIA.")

In [ ]:
# Teste de KPSS
resultado_kpss = kpss(
    df["Price_Normalizado"].dropna(),
    regression="c",
    nlags="auto"
)

print("\nTeste KPSS")
print("Estatística:", resultado_kpss[0])
print("P-valor:", resultado_kpss[1])

if resultado_kpss[1] < 0.05:
    print("Resultado: A série NÃO é estacionária.\n")
else:
    print("Resultado: A série é ESTACIONÁRIA.\n")

### **Gráficos Estatísticos**

#### ACF

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

serie = df["Price_Normalizado"].dropna()

plt.figure(figsize=(10, 5))
plot_acf(serie, lags=40, ax=plt.gca())

plt.title("ACF - Dow Jones")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

In [ ]:
serie = df["Price"].dropna()

plt.figure(figsize=(10, 5))
plot_acf(serie, lags=40, ax=plt.gca())

plt.title("ACF - Dow Jones")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

#### PACF

In [ ]:
serie = df["Price_Normalizado"].dropna()

plt.figure(figsize=(10, 5))
plot_pacf(serie, lags=40, ax=plt.gca(), method="ywm")

plt.title("PACF - Dow Jones")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação parcial")
plt.show()

In [ ]:
serie = df["Price"].dropna()

plt.figure(figsize=(10, 5))
plot_pacf(serie, lags=40, ax=plt.gca(), method="ywm")

plt.title("PACF - Dow Jones")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação parcial")
plt.show()

#### **Conclusão**

ACF e PACF:

**O gráfico de ACF apresenta autocorrelações muito elevadas nas primeiras defasagens, permanecendo próximas de 1 mesmo para lags mais elevados**. A **autocorrelação apresenta uma redução muito lenta, indicando forte persistência e dependência temporal dos valores do índice Dow Jones**.

No gráfico de PACF, observam-se **picos significativos principalmente nas primeiras defasagens**, especialmente nos lags 1 e 2. A partir do terceiro lag, os **valores ficam próximos de zero e, em sua maioria, dentro do intervalo de confiança**. Esse **comportamento indica que as primeiras defasagens possuem maior influência direta sobre a série**. Em conjunto, **os gráficos de ACF e PACF reforçam a presença de forte dependência temporal e são compatíveis com a não estacionariedade** observada anteriormente na série de preços.

##**Primeira Diferença**

In [ ]:
serie_diff = df["Price_Normalizado"].diff().dropna()
print(serie_diff.head())

In [ ]:
resultado_adf = adfuller(serie_diff)

print("Teste ADF - Série Diferenciada")
print("Estatística:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

if resultado_adf[1] < 0.05:
    print("A série diferenciada é ESTACIONÁRIA.")
else:
    print("A série diferenciada NÃO é estacionária.")

In [ ]:
plt.figure(figsize=(12, 5))
plt.plot(serie_diff)

plt.title("Primeira Diferença - Dow Jones", fontweight='bold')
plt.xlabel("Data", fontweight='bold')
plt.ylabel("Diferença", fontweight='bold')
plt.show()

In [ ]:
plt.figure(figsize=(10, 5))
plot_acf(serie_diff, lags=40, ax=plt.gca())

plt.title("ACF - Dow Jones após Primeira Diferença", fontweight='bold')
plt.xlabel("Defasagem (Lag)", fontweight='bold')
plt.ylabel("Autocorrelação", fontweight='bold')
plt.show()

In [ ]:
plt.figure(figsize=(10, 5))
plot_pacf(
    serie_diff,
    lags=40,
    ax=plt.gca(),
    method="ywm"
)

plt.title("PACF - Dow Jones após Primeira Diferença", fontweight='bold')
plt.xlabel("Defasagem (Lag)", fontweight='bold')
plt.ylabel("Autocorrelação Parcial", fontweight='bold')
plt.show()

## **Conclusão do Índice Dow Jones**

Sim. **Após a aplicação da primeira diferença**, a série **tornou-se estacionária**. O teste **ADF apresentou p-valor inferior a 0,05**, permitindo **rejeitar a hipótese nula de presença de raiz unitária**. Além disso, os gráficos de **ACF e PACF da série diferenciada apresentam autocorrelações próximas de zero na maior parte das defasagens**, indicando **redução significativa da dependência temporal** observada na série original.

#**Parte 2: PIB Trimestral (Consumo das Famílias)**
Siga os passos abaixo para analisar a série do PIB Trimestral:

Obtenção dos Dados:
* Obtenha a série de código 22100 referente ao PIB Trimestral - Consumo das famílias (utilize a biblioteca DadosAbertosBrasil ou o sistema SGS do Banco Central).

Análise Descritiva e Decomposição:
* Plote o gráfico da série original e identifique visualmente se há tendência, sazonalidade ou outliers.
* Aplique os métodos de Decomposição de Séries Temporais (Tendência, Sazonalidade e Símbolo/Resíduo) e escreva suas conclusões.


Avaliação de Estacionariedade e Autocorrelação:
* Execute os testes ADF e KPSS e interprete os p-valores obtidos em relação às hipóteses nulas.
* Plote e interprete as funções de autocorrelação (ACF e PACF).

Diferenciação
* Se necessário, aplique diferenciações na série para torna-la estacionária.
* Recompute os testes ADF, KPSS e atualize os gráficos de ACF/PACF.

**Responda**: **Quantas diferenciações foram necessárias para estacionalizar a série?** Algum fator (outlier, picos atípicos) chamou sua atenção?

## **Análise Inicial**

In [ ]:
import pandas as pd
from bcb import sgs

df_pib = sgs.get(
    {"PIB_Consumo_Familias": 22100},
    start="1995-01-01",
    end="2026-03-31"
)

df_pib = df_pib.reset_index()
df_pib = df_pib.rename(
    columns={
        "Date": "data",
        "PIB_Consumo_Familias": "valor"
    }
)

print(df_pib.head())

In [ ]:
df_pib["data"] = pd.to_datetime(df_pib["data"], dayfirst=True)

df_pib["valor"] = pd.to_numeric(
    df_pib["valor"],
    errors="coerce"
)

df_pib.set_index("data", inplace=True)
df_pib.sort_index(inplace=True)
df_pib.head()

In [ ]:
df_pib.info()

In [ ]:
df_pib.rename(columns={"valor": "PIB_Consumo"}, inplace=True)
df_pib.head()

###**Gráfico Inicial**

In [ ]:
df_pib.plot(figsize=(20, 6))
plt.title("PIB Trimestral - Consumo das Famílias", fontweight='bold')
plt.xlabel("Data", fontweight='bold')
plt.ylabel("PIB", fontweight='bold')
plt.grid(True)
plt.show()

In [ ]:
from statsmodels.tsa.seasonal import seasonal_decompose
decomposicao = seasonal_decompose(
    df_pib["PIB_Consumo"],
    model="additive",
    period=4
)

decomposicao.plot()
plt.show()

### **Resposta da análise gráfica da série do PIB Trimestral**:
Consumo das Famílias **evidencia uma tendência crescente** ao longo do período analisado. **O componente de tendência confirma esse comportamento**, apresentando **crescimento de longo prazo**, **embora existam períodos de desaceleração e pequenas quedas**, especialmente entre 2015 e 2016.

**O componente sazonal apresenta um padrão bastante regular**, que se repete a cada **quatro observações**, confirmando **a existência de sazonalidade trimestral**. Em relação aos resíduos, a maior parte dos valores permanece próxima de zero, indicando que **a tendência e a sazonalidade explicam boa parte do comportamento da série**. Entretanto, observam-se algumas variações mais acentuadas, com **destaque para o período de 2020, que apresenta um resíduo negativo bastante expressivo, caracterizando uma possível variação atípica - Devido a COVID-19**. Portanto, a **série apresenta tendência crescente, sazonalidade trimestral bem definida e alguns períodos de comportamento atípico**.

## **Testes Estatísticos**

### **Normalização dos Dados**

In [ ]:
import scipy.stats as stats
import matplotlib.pyplot as plt

stats.probplot(df_pib["PIB_Consumo"].dropna(), dist="norm", plot=plt)

plt.title("QQ Plot - Valores de PIB")
plt.show()

In [ ]:
from scipy.stats import shapiro

resultado = shapiro(df_pib["PIB_Consumo"].dropna())

print("Estatística:", resultado.statistic)
print("P-valor:", resultado.pvalue)

if resultado.pvalue < 0.05:
    print("Os dados NÃO apresentam distribuição normal.")
else:
    print("Os dados apresentam distribuição normal.")

In [ ]:
df_pib["Retorno"] = df_pib["PIB_Consumo"].pct_change()
df_pib["Retorno"].dropna().head()

In [ ]:
stats.probplot(df_pib["Retorno"].dropna(), dist="norm", plot=plt)

plt.title("QQ Plot - Retorno dos Valores de PIB")
plt.show()

In [ ]:
from scipy.stats import shapiro

resultado = shapiro(df_pib["Retorno"].dropna())

print("Estatística:", resultado.statistic)
print("P-valor:", resultado.pvalue)

if resultado.pvalue < 0.05:
    print("Os dados NÃO apresentam distribuição normal.")
else:
    print("Os dados apresentam distribuição normal.")

### **Ajuste na Normalização**

In [ ]:
from sklearn.preprocessing import StandardScaler

serie = df_pib["PIB_Consumo"].dropna()
scaler = StandardScaler()
df_pib["PIB_Consumo_Normalizado"] = scaler.fit_transform(
    df_pib[["PIB_Consumo"]]
)

print("Média:", df_pib["PIB_Consumo_Normalizado"].mean())
print("Desvio padrão:", df_pib["PIB_Consumo_Normalizado"].std())

In [ ]:
stats.probplot(
    df_pib["PIB_Consumo_Normalizado"].dropna(),
    dist="norm",
    plot=plt
)

plt.title("QQ Plot - PIB Consumo Normalizado")
plt.show()

In [ ]:
sns.distplot(df_pib["PIB_Consumo_Normalizado"].dropna())
plt.show()

In [ ]:
sns.histplot(df_pib["PIB_Consumo"].dropna(), kde=True)
plt.show()

### **Teste Estatístico**

In [ ]:
# Teste de ADF
from statsmodels.tsa.stattools import adfuller

resultado_adf = adfuller(df_pib["PIB_Consumo_Normalizado"].dropna())

print("Teste ADF")
print("Estatística:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

if resultado_adf[1] < 0.05:
    print("Resultado: A série é ESTACIONÁRIA.")
else:
    print("Resultado: A série NÃO é ESTACIONÁRIA.")

In [ ]:
# Teste de KPSS
resultado_kpss = kpss(
    df_pib["PIB_Consumo_Normalizado"].dropna(),
    regression="c",
    nlags="auto"
)

print("\nTeste KPSS")
print("Estatística:", resultado_kpss[0])
print("P-valor:", resultado_kpss[1])

if resultado_kpss[1] < 0.05:
    print("Resultado: A série NÃO é estacionária.\n")
else:
    print("Resultado: A série é ESTACIONÁRIA.\n")

### **Gráficos Estatísticos**

#### ACF

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

serie = df_pib["PIB_Consumo_Normalizado"].dropna()

plt.figure(figsize=(10, 5))
plot_acf(serie, lags=40, ax=plt.gca())

plt.title("ACF - PIB Consumo Normalizado")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

#### PACF

In [ ]:
serie = df_pib["PIB_Consumo_Normalizado"].dropna()

plt.figure(figsize=(10, 5))
plot_pacf(serie, lags=40, ax=plt.gca(), method="ywm")

plt.title("PACF - PIB Consumo Normalizado")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação parcial")
plt.show()

#### **Conclusão**

ACF e PACF:
A ACF do PIB de Consumo Normalizado apresenta **autocorrelações positivas e elevadas em diversos lags**, com uma **redução gradual ao longo das defasagens**. Esse comportamento indica f**orte dependência temporal e persistência dos valores da série**. A autocorrelação permanece significativa por vários períodos, sugerindo a **presença de tendência e/ou não estacionariedade na série**. Como a série é trimestral, o lag 4 representa aproximadamente a comparação com o mesmo trimestre do ano anterior.

A PACF do PIB de Consumo Normalizado apresenta uma **forte autocorrelação parcial no primeiro lag**, indicando uma **relação direta elevada entre o valor atual e o período imediatamente anterior**. Após o primeiro lag, a maioria das autocorrelações parciais permanece **próxima de zero e dentro do intervalo de confiança**, embora alguns lags apresentem valores estatisticamente significativos. Em conjunto com a ACF, que apresenta uma queda lenta das autocorrelações, o resultado **reforça a existência de forte dependência temporal e indica que a série em nível apresenta características de não estacionariedade**

##**Primeira Diferença**

In [ ]:
serie_diff = df_pib["PIB_Consumo_Normalizado"].diff().dropna()
print(serie_diff.head())

In [ ]:
resultado_adf = adfuller(serie_diff)

print("Teste ADF - Série Diferenciada")
print("Estatística:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

if resultado_adf[1] < 0.05:
    print("A série diferenciada é ESTACIONÁRIA.")
else:
    print("A série diferenciada NÃO é estacionária.")

## **Segunda Diferença**

In [ ]:
resultado_adf_diff = adfuller(serie_diff)

if resultado_adf_diff[1] < 0.05:
    print("A série está estacionária!\n")
    serie_estacionaria = serie_diff
    numero_diferencas = 1

else:
    print("A série NÃO está estacionária após a primeira diferenciação!\n")
    serie_diff2 = serie_diff.diff().dropna()
    resultado_adf_diff2 = adfuller(serie_diff2)
    print("Aplicando segunda diferenciação...")

    if resultado_adf_diff2[1] < 0.05:
        print("A série está estacionária!")
        serie_estacionaria = serie_diff2
        numero_diferencas = 2
    else:
        print("A série ainda NÃO está estacionária!")
        serie_estacionaria = serie_diff2
        numero_diferencas = 2

print("\nNúmero de diferenciações:", numero_diferencas)
print("P-valor ADF:", adfuller(serie_estacionaria)[1])

In [ ]:
# ACF
plt.figure(figsize=(10, 5))
plot_acf(serie_estacionaria, lags=40, ax=plt.gca())
plt.title("ACF - PIB após Diferenciação")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

# PACF
plt.figure(figsize=(10, 5))
plot_pacf(serie_estacionaria, lags=40, ax=plt.gca(), method="ywm")
plt.title("PACF - PIB após Diferenciação")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação Parcial")
plt.show()

##**Conclusão**

Após a **aplicação da primeira diferenciação**, a série **não se tornou estacionária**, **conforme indicado pelo teste ADF**. Dessa forma, foi **aplicada uma segunda diferenciação**.

Após a segunda diferenciação, a série tornou-se **estacionária**, apresentando **p-valor inferior a 0,05**.

Nos gráficos de **ACF e PACF após a segunda diferenciação**, observa-se uma redução da dependência da série. A **ACF ainda apresenta alguns picos, principalmente nos lags múltiplos de 4**, indicando um possível padrão sazonal trimestral. Na **PACF**, os maiores picos aparecem nas primeiras defasagens, especialmente nos lags 1, 2 e 3.

Conclui-se que **foram necessárias duas diferenciações para tornar a série estacionária**. Apesar da estacionarização, os gráficos de **ACF e PACF indicam que a componente sazonal trimestral** ainda apresenta influência na série

#**Parte 3: Vendas no Varejo (Série Sazonal)**
Siga os passos abaixo para avaliar uma série com forte padrão sazonal:

Obtenção dos Dados

* Extraia a série de código 1455 do BACEN (Índice do volume de vendas no varejo - Total - Brasil).

* Filtre o período de análise entre '2014-01' e '2020-01'.

Decomposição e Testes Iniciais

* Plote o gráfico da série temporal e faça a decomposição em tendência e sazonalidade.

* Execute os testes ADF e KPSS e plote o ACF e PACF para a série original.

Tratamento de Sazonalidade

* Aplique a diferença simples e/ou a diferença sazonal para remover padrões de tendência e sazonalidade.

* Refaça os testes estatísticos e plote a nova ACF e PACF.

**Responda: Qual foi o impacto da diferença sazonal na busca pela estacionariedade?**

## **Obtenção dos Dados**

In [ ]:
'''
import bcb
%pip show python-bcb
import pandas as pd

print("python-bcb:", bcb.__version__)
print("pandas:", pd.__version__)
'''

In [ ]:
import pandas as pd
from bcb import sgs

df = sgs.get(
    {"Vendas_Varejo": 1455},
    start="2014-01-01",
    end="2020-01-31"
)


df = df.reset_index()
df = df.rename(columns={"Date": "data"})
df["periodo"] = df["data"].dt.to_period("M")

df = df[
    (df["periodo"] >= "2014-01") &
    (df["periodo"] <= "2020-01")
].copy()

df = df[["periodo", "Vendas_Varejo"]].reset_index(drop=True)

In [ ]:
df_copia = df.copy()
df_copia.rename(columns={"valor": "Vendas_Varejo"}, inplace=True)
df_copia.set_index("periodo", inplace=True)
df_copia.head()

In [ ]:
df_copia.info()

## **Criação da Série Temporal**

In [ ]:
df_copia.plot(figsize=(20, 6))
plt.title("BACEN - VENDAS DE VAREJO", fontweight='bold')
plt.xlabel("Data", fontweight='bold')
plt.ylabel("Valores", fontweight='bold')
plt.grid(True)
plt.show()

## **Testes Estatísticos**

In [ ]:
# Teste de ADF
from statsmodels.tsa.stattools import adfuller

resultado_adf = adfuller(df_copia["Vendas_Varejo"].dropna())

print("Teste ADF")
print("Estatística:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

if resultado_adf[1] < 0.05:
    print("Resultado: A série é ESTACIONÁRIA.")
else:
    print("Resultado: A série NÃO é ESTACIONÁRIA.")

In [ ]:
# Teste de KPSS
resultado_kpss = kpss(
    df_copia["Vendas_Varejo"].dropna(),
    regression="c",
    nlags="auto"
)

print("\nTeste KPSS")
print("Estatística:", resultado_kpss[0])
print("P-valor:", resultado_kpss[1])

if resultado_kpss[1] < 0.05:
    print("Resultado: A série NÃO é estacionária.\n")
else:
    print("Resultado: A série é ESTACIONÁRIA.\n")

### **Gráficos Estatísticos**

#### ACF

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

serie = df_copia["Vendas_Varejo"].dropna()

plt.figure(figsize=(20, 5))
plot_acf(serie, lags=40, ax=plt.gca())

plt.title("ACF - BACEN Vendas Varejo")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

#### PACF

In [ ]:
serie = df_copia["Vendas_Varejo"].dropna()

plt.figure(figsize=(20, 5))
plot_pacf(serie, lags=36, ax=plt.gca(), method="ywm")

plt.title("PACF - BACEN Vendas Varejo")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação parcial")
plt.show()

#### **Conclusão**

ACF e PACF:
A análise da função de autocorrelação (ACF) evidencia **a presença de dependência temporal e de um padrão sazonal**. Observa-se uma autocorrelação positiva no primeiro lag, **indicando que os valores das vendas apresentam relação com os valores observados no mês anterior**. Destaca-se, entretanto, a **elevada autocorrelação no lag 12**, aproximadamente 0,75, que **ultrapassa o intervalo de confiança**. Como a série possui frequência mensal, o lag 12 representa **a relação entre um determinado mês e o mesmo mês do ano anterior**, constituindo uma forte evidência de sazonalidade anual. Também são observados picos **positivos nos lags 24 e 36**, correspondentes a **dois e três anos de defasagem**, respectivamente. **A presença de autocorrelações nos múltiplos de 12 reforça a existência de um padrão sazonal anual na série**, justificando a utilização de período sazonal igual a 12 na decomposição da série temporal.

A análise da função de autocorrelação parcial (PACF) **evidencia a existência de dependência temporal na série de vendas no varejo**. Observa-se um pico **positivo no primeiro lag**, **indicando dependência entre as vendas de um mês e as vendas do mês anterior**. Entretanto, o **resultado de maior destaque ocorre no lag 12**, que apresenta autocorrelação parcial próxima de 0,70 e ultrapassa significativamente o intervalo de confiança. Como a **série possui frequência mensal**, o lag 12 corresponde a um período de um ano, reforçando a evidência de um **componente sazonal anual identificada anteriormente pela ACF**. Também se observa um pico negativo no lag 13, que pode estar relacionado à estrutura da dependência sazonal da série. Em conjunto com a ACF, os resultados sugerem que a série apresenta forte componente sazonal com periodicidade de 12 meses.

A **ACF e a PACF indicam forte sazonalidade anual na série de vendas do varejo, evidenciada principalmente pelos elevados picos associados à defasagem de 12 meses**. Dessa forma, a periodicidade sazonal considerada nos modelos deve ser de 12 meses (s = 12).

##**Diferença Sazonal**

In [ ]:
from statsmodels.tsa.stattools import adfuller

df_copia["Vendas_Varejo"] = pd.to_numeric(
    df_copia["Vendas_Varejo"],
    errors="coerce"
)

# Diferença sazonal de 12 meses
serie_diff = df_copia["Vendas_Varejo"].diff(12).dropna()

print(serie_diff.head())

###**Testes Estatisticos**

In [ ]:
# Teste ADF
resultado_adf = adfuller(serie_diff)

print("\nTeste ADF - Série com Diferença Sazonal")
print("Estatística ADF:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

# Decisão
if resultado_adf[1] < 0.05:
    print("A série diferenciada é ESTACIONÁRIA.")
else:
    print("A série diferenciada NÃO é estacionária.")

In [ ]:
# Teste de KPSS
resultado_kpss = kpss(
    serie_diff,
    regression="c",
    nlags="auto"
)

print("\nTeste KPSS")
print("Estatística:", resultado_kpss[0])
print("P-valor:", resultado_kpss[1])

if resultado_kpss[1] < 0.05:
    print("Resultado: A série NÃO é estacionária.\n")
else:
    print("Resultado: A série é ESTACIONÁRIA.\n")

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 5))
plot_acf(serie_diff, lags=40, ax=plt.gca())

plt.title("ACF - BACEN Vendas Varejo")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

In [ ]:
plt.figure(figsize=(20, 5))
plot_pacf(serie_diff, lags=30, ax=plt.gca(), method="ywm")

plt.title("PACF - BACEN Vendas Varejo")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação parcial")
plt.show()

###**Conclusão**
A diferença sazonal foi aplicada para remover a sazonalidade,**mas os seus testes mostram que ela não foi suficiente para tornar a série estacionária**.

##Segunda Tentativa

In [ ]:
serie_diff_final = serie_diff.diff().dropna()

In [ ]:
# ADF
resultado_adf = adfuller(serie_diff_final)

print("=== ADF ===")
print("Estatística:", resultado_adf[0])
print("P-valor:", resultado_adf[1])

if resultado_adf[1] < 0.05:
    print("A série diferenciada é ESTACIONÁRIA.")
else:
    print("A série diferenciada NÃO é estacionária.")


# KPSS
resultado_kpss = kpss(
    serie_diff_final,
    regression="c",
    nlags="auto"
)

print("\n=== KPSS ===")
print("Estatística:", resultado_kpss[0])
print("P-valor:", resultado_kpss[1])
if resultado_kpss[1] < 0.05:
    print("Resultado: A série NÃO é estacionária.\n")
else:
    print("Resultado: A série é ESTACIONÁRIA.\n")

In [ ]:
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 5))
plot_acf(serie_diff_final, lags=40, ax=plt.gca())

plt.title("ACF - BACEN Vendas Varejo")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação")
plt.show()

In [ ]:
plt.figure(figsize=(20, 5))
plot_pacf(serie_diff_final, lags=30, ax=plt.gca(), method="ywm")

plt.title("PACF - BACEN Vendas Varejo")
plt.xlabel("Defasagem (Lag)")
plt.ylabel("Autocorrelação parcial")
plt.show()

###**Conclusão Final**

Após a aplicação da diferença sazonal e de uma diferença regular, o **teste ADF** rejeita a hipótese nula de raiz unitária, **indicando estacionariedade**. Entretanto, o **teste KPSS ainda rejeita a hipótese nula de estacionariedade ao nível de 5%**. Dessa forma, os testes apresentam resultados **divergentes, sendo necessário avaliar a série com cautela e considerar análises complementares antes de afirmar definitivamente que ela é estacionária**.