In [ ]:
'''
    @author: Matheus Lopes
    @date: 08-04-2026
    @description: Aula 1 - Conhecimentos Básicos de Python para Ciência de Dados

    Conhecimentos iniciais de python, onde estamos instalando o python e outras bibliotecas!
    -> Essa parte já está feita, então vamos para o código!

    https://leandrolessa.com.br/tutoriais/virtualenv-em-python-em-6-passos/
    https://leandrolessa.com.br/dados/4-razoes-para-utilizar-virtualenv-em-projetos-python/

    virtualenv -p python3 {nome do ambiente}
    Scripts\activate
    deactivate
'''

'\n    @author: Matheus Lopes\n    @date: 08-04-2026\n    @description: Aula 1 - Conhecimentos Básicos de Python para Ciência de Dados\n\n    Conhecimentos iniciais de python, onde estamos instalando o python e outras bibliotecas!\n    -> Essa parte já está feita, então vamos para o código!\n'

In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [32]:
df = pd.read_csv('C:\\Users\\negri\\OneDrive\\Documentos\\GitHub\\Hashtag_AnaliseDados\\Python\\Cursos\\PUC Ciência de Dados\\Dataset\\precos_imoveis.csv', sep='|')

In [33]:
df.head()

   area  garagem  banheiros  lareira  marmore  andares  preco  id_estado
0    25        3          4        3        0        1  51875          7
1    35        1          3        1        0        0  17875         21
2   195        2          4        2        0        0  47075          8
3    33        2          2        1        0        1  38575         16
4    11        2          3        0        0        1  33775         14

In [ ]:
df_preco = df.copy()
df_preco['preco'] = df['preco'].apply(lambda x:'{:,.2f}'.format(x)) # Padrão Americano de formatação númerica
df_preco.head()

   area  garagem  banheiros  lareira  marmore  andares      preco  id_estado
0    25        3          4        3        0        1  51,875.00          7
1    35        1          3        1        0        0  17,875.00         21
2   195        2          4        2        0        0  47,075.00          8
3    33        2          2        1        0        1  38,575.00         16
4    11        2          3        0        0        1  33,775.00         14